/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.belajarjava.app;

import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author Rino
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneBackground2 = new com.belajarjava.app.JDesktopPaneBackground();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInput = new javax.swing.JMenu();
        menuItemPelanggan = new javax.swing.JMenuItem();
        menuItemDataBuku = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuItemPenjualanBuku = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuItemLaporan = new javax.swing.JMenuItem();
        menuItemLaporanBuku = new javax.swing.JMenuItem();
        menuItemLaporanPelanggan = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuInput.setText("Input");

        menuItemPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/User_24x24.png"))); // NOI18N
        menuItemPelanggan.setText("Data Pelanggan");
        menuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPelangganActionPerformed(evt);
            }
        });
        menuInput.add(menuItemPelanggan);

        menuItemDataBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuItemDataBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/Picture_24x24.png"))); // NOI18N
        menuItemDataBuku.setText("Data Buku");
        menuItemDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDataBukuActionPerformed(evt);
            }
        });
        menuInput.add(menuItemDataBuku);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/Log Out_24x24.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuInput.add(menuItemExit);

        jMenuBar1.add(menuInput);

        menuTransaksi.setText("Transaksi");

        menuItemPenjualanBuku.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPenjualanBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/Save_24x24.png"))); // NOI18N
        menuItemPenjualanBuku.setText("Penjualan Buku");
        menuItemPenjualanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPenjualanBukuActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuItemPenjualanBuku);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setText("Laporan");

        menuItemLaporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuItemLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/Print_24x24.png"))); // NOI18N
        menuItemLaporan.setText("Laporan Penjualan");
        menuItemLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporan);

        menuItemLaporanBuku.setText("Laporan Data Buku");
        menuItemLaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanBukuActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporanBuku);

        menuItemLaporanPelanggan.setText("Laporan Data Pelanggan");
        menuItemLaporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLaporanPelangganActionPerformed(evt);
            }
        });
        menuLaporan.add(menuItemLaporanPelanggan);

        jMenuBar1.add(menuLaporan);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/belajarjava/app/gambar/Help_24x24.png"))); // NOI18N
        jMenuItem1.setText("Tentang Aplikasi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAbout.add(jMenuItem1);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualanBuku laporanPenjualanBuku=new LaporanPenjualanBuku();
        jDesktopPaneBackground2.add(laporanPenjualanBuku);
        laporanPenjualanBuku.setVisible(true);
    }//GEN-LAST:event_menuItemLaporanActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        int jawab=JOptionPane.showOptionDialog(this, "Yakin ingin Keluar", "Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (jawab==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
        
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPelangganActionPerformed
        // TODO add your handling code here:
        FrmPelanggan pelanggan=new FrmPelanggan();
        jDesktopPaneBackground2.add(pelanggan);
        pelanggan.setVisible(true);
        
    }//GEN-LAST:event_menuItemPelangganActionPerformed

    private void menuItemLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanBukuActionPerformed
        // TODO add your handling code here:
        LaporanDataBuku laporanDataBuku=new LaporanDataBuku();
        jDesktopPaneBackground2.add(laporanDataBuku);
        laporanDataBuku.setVisible(true);
    }//GEN-LAST:event_menuItemLaporanBukuActionPerformed

    private void menuItemDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDataBukuActionPerformed
        // TODO add your handling code here:
        FrmBuku buku=new FrmBuku();
        jDesktopPaneBackground2.add(buku);
        buku.setVisible(true);
    }//GEN-LAST:event_menuItemDataBukuActionPerformed

    private void menuItemPenjualanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPenjualanBukuActionPerformed
        // TODO add your handling code here:
        FrmPenjualanBuku jualBuku=new FrmPenjualanBuku();
        jDesktopPaneBackground2.add(jualBuku);
        jualBuku.setVisible(true);
    }//GEN-LAST:event_menuItemPenjualanBukuActionPerformed

    private void menuItemLaporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLaporanPelangganActionPerformed
        // TODO add your handling code here:
        LaporanDataPelanggan laporanDataPelanggan=new LaporanDataPelanggan();
        jDesktopPaneBackground2.add(laporanDataPelanggan);
        laporanDataPelanggan.setVisible(true);
    }//GEN-LAST:event_menuItemLaporanPelangganActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAboutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmAbout frmAbout=new FrmAbout();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.belajarjava.app.JDesktopPaneBackground jDesktopPaneBackground2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuInput;
    private javax.swing.JMenuItem menuItemDataBuku;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLaporan;
    private javax.swing.JMenuItem menuItemLaporanBuku;
    private javax.swing.JMenuItem menuItemLaporanPelanggan;
    private javax.swing.JMenuItem menuItemPelanggan;
    private javax.swing.JMenuItem menuItemPenjualanBuku;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
